### ISSUE TITLE
Error "knowreservations" package

### ISSUE THREAD

**Issue by euphoriatek** [highlandvision/knowres#1]
Hello,
I've installed the "knowreservations" package (version 4.2.0) on my local Joomla 4.4 instance with PHP version 8.0.28 and MySQL version 5.2.1. After adding new properties in the component, we're encountering an error.
![image (1)](https://github.com/highlandvision/knowres/assets/3530578/5d4246ca-42b1-407d-8386-2582e76a5587)

**Comment by highlandvision** [comment]
What were you doing before the error displayed? e.g. admin or site, page, form etc

Thanks!

**Comment by highlandvision** [comment]
Closed, no response.
